name: "Run unit tests"
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - "server/src/main/java/*"
      - "server/src/test/java/*"
      - ".github/workflows/*"
jobs:
  run_unit_tests:
    name: "Running unit tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Run Tests
        run: |
          cd server
          mvn test
