def heroes():
    heroes = [
    ('Superman', 'Clark Kent', 35, 'Male', 'Superhuman strength, speed, flight, heat vision', 'Kryptonite, magic', 'Justice League'),
    ('Batman', 'Bruce Wayne', 40, 'Male', 'Genius-level intellect, martial arts mastery, detective skills', 'No superpowers, trauma', 'Justice League'),
    ('Wonder Woman', 'Diana Prince', 5000, 'Female', 'Superhuman strength, speed, agility, flight, Lasso of Truth', 'Vulnerability to piercing weapons, magic', 'Justice League'),
    ('The Flash', 'Barry Allen', 30, 'Male', 'Superhuman speed, time manipulation', 'Time paradoxes, Speed Force instability', 'Justice League'),
    ('Green Lantern', 'Hal Jordan', 35, 'Male', 'Power ring constructs, flight, energy manipulation', 'Vulnerability to fear, ring\'s charge limitations', 'Justice League'),
    ('Aquaman', 'Arthur Curry', 35, 'Male', 'Superhuman strength, speed, underwater adaptation, telepathic control over marine life', 'Vulnerability to dehydration, magic', 'Justice League'),
    ('Cyborg', 'Victor Stone', 25, 'Male', 'Cybernetic enhancements, superhuman strength, technopathy', 'Struggles with humanity, cybernetic vulnerabilities', 'Justice League'),
    ('Shazam', 'Billy Batson', 15, 'Male', 'Transformation into superhuman adult with various abilities', 'Limited control over powers, vulnerability to magic', 'Justice League'),
    ('Green Arrow', 'Oliver Queen', 35, 'Male', 'Master archer, skilled martial artist, trick arrows', 'No superpowers, mortality', 'Justice League'),
    ('Martian Manhunter', 'J\'onn J\'onzz', 3000, 'Male', 'Superhuman strength, shapeshifting, telepathy, intangibility, flight', 'Vulnerability to fire, mental instability', 'Justice League'),
    ('Black Canary', 'Dinah Lance', 30, 'Female', 'Expert martial artist, supersonic Canary Cry', 'No superpowers, mortality', 'Justice League'),
    ('Hawkman', 'Carter Hall', 4000, 'Male', 'Reincarnated warrior, flight, enhanced strength, weapons mastery', 'Reincarnation cycle, vulnerability to Nth metal', 'Justice League'),
    ('Hawkgirl', 'Shiera Hall', 4000, 'Female', 'Reincarnated warrior, flight, enhanced strength, weapons mastery', 'Reincarnation cycle, vulnerability to Nth metal', 'Justice League'),
    ('Zatanna', 'Zatanna Zatara', 30, 'Female', 'Magic spells, incantations, skilled magician', 'Dependency on spoken magic, vulnerability to certain spells', 'Justice League'),
    ('Doctor Fate', 'Kent Nelson', 50, 'Male', 'Magic spells, flight, precognition', 'Dependency on Helmet of Fate, vulnerability to chaos magic', 'Justice League'),
    ('Batgirl', 'Barbara Gordon', 25, 'Female', 'Skilled martial artist, detective skills, technology expertise', 'No superpowers, mortality', 'Bat Family'),
    ('Nightwing', 'Dick Grayson', 30, 'Male', 'Acrobatics, martial arts mastery, detective skills', 'No superpowers, mortality', 'Bat Family'),
    ('Robin', 'Damian Wayne', 15, 'Male', 'Acrobatics, martial arts mastery, detective skills', 'No superpowers, mortality', 'Bat Family'),
    ('Supergirl', 'Kara Zor-El', 25, 'Female', 'Superhuman strength, speed, flight, heat vision', 'Vulnerability to kryptonite, magic', 'Justice League'),
    ('Red Hood', 'Jason Todd', 25, 'Male', 'Skilled marksman, hand-to-hand combatant, technology expertise', 'No superpowers, mortality, trauma', 'Bat Family'),
    ('Green Lantern (John Stewart)', 'John Stewart', 35, 'Male', 'Power ring constructs, flight, energy manipulation', 'Vulnerability to fear, ring\'s charge limitations', 'Justice League'),
    ('Green Lantern (Kyle Rayner)', 'Kyle Rayner', 30, 'Male', 'Power ring constructs, flight, energy manipulation', 'Vulnerability to fear, ring\'s charge limitations', 'Justice League'),
    ('Green Lantern (Jessica Cruz)', 'Jessica Cruz', 25, 'Female', 'Power ring constructs, flight, energy manipulation', 'Vulnerability to fear, ring\'s charge limitations', 'Justice League'),
    ('Booster Gold', 'Michael Jon Carter', 35, 'Male', 'Flight, energy blasts, force field projection', 'Narcissism, irresponsibility', 'Justice League'),
    ('Blue Beetle', 'Jaime Reyes', 20, 'Male', 'Scarab-derived armor, flight, energy blasts', 'Struggles with controlling the scarab, vulnerability to mental influence', 'Justice League'),
    ('Huntress', 'Helena Bertinelli', 30, 'Female', 'Expert markswoman, martial artist, crossbow proficiency', 'No superpowers, mortality, vigilante ethics', 'Bat Family'),
    ('Swamp Thing', 'Alec Holland', 'Ageless', 'Male', 'Plant manipulation, elemental control, superhuman strength', 'Vulnerability to fire, limited mobility outside of plant life', 'Justice League Dark'),
    ('Constantine', 'John Constantine', 45, 'Male', 'Expert sorcerer, occult knowledge, manipulation', 'Cynicism, moral ambiguity, demonic debts', 'Justice League Dark'),
    ('Zatara', 'Giovanni Zatara', 60, 'Male', 'Magic spells, incantations, skilled magician', 'Dependency on spoken magic, vulnerability to certain spells', 'Justice League Dark'),
    ('Deadman', 'Boston Brand', 'Ageless', 'Male', 'Invisibility, possession, acrobatics', 'Guilt over past, inability to interact with physical world', 'Justice League Dark'),
    ('Cyborg Superman', 'Hank Henshaw', 'Ageless', 'Male', 'Cybernetic enhancements, superhuman strength, technopathy', 'Struggles with humanity, cybernetic vulnerabilities', 'None'),
    ('Firestorm', 'Ronnie Raymond/Martin Stein', 25, 'Male', 'Transmutation, energy manipulation, flight', 'Dependency on fusion, mental conflicts', 'Justice League'),
    ('Black Lightning', 'Jefferson Pierce', 40, 'Male', 'Electrokinesis, flight, expert martial artist', 'Responsibility to community, family dynamics', 'Justice League'),
    ('Atom', 'Ray Palmer', 40, 'Male', 'Size manipulation, genius-level intellect, hand-to-hand combat', 'Struggles with personal relationships, size limitations', 'Justice League'),
    ('Plastic Man', 'Patrick "Eel" O\'Brian', 40, 'Male', 'Elasticity, shapeshifting, durability', 'Lack of seriousness, goofy personality', 'Justice League'),
    ('Vixen', 'Mari Jiwe McCabe', 30, 'Female', 'Animal mimicry, enhanced strength, speed, agility', 'Struggles with balancing her personal life and hero duties', 'Justice League'),
    ('The Atom (Ryan Choi)', 'Ryan Choi', 30, 'Male', 'Size manipulation, genius-level intellect, hand-to-hand combat', 'Struggles with personal relationships, size limitations', 'Justice League'),
    ('Metamorpho', 'Rex Mason', 30, 'Male', 'Elemental transmutation, shapeshifting, superhuman strength', 'Physical appearance, emotional instability', 'Justice League'),
    ('Hawk', 'Hank Hall', 35, 'Male', 'Enhanced strength, combat skills', 'Struggles with aggression, violent tendencies', 'Justice League'),
    ('Dove', 'Don Hall', 'Ageless', 'Male', 'Flight, energy blasts', 'Struggles with confidence, violent tendencies', 'Justice League'),
    ('Hawk and Dove', 'Holly Granger', 25, 'Female', 'Enhanced strength, combat skills', 'Struggles with aggression, violent tendencies', 'Justice League'),
    ('John Constantine', 'John Constantine', 45, 'Male', 'Expert sorcerer, occult knowledge, manipulation', 'Cynicism, moral ambiguity, demonic debts', 'Justice League Dark'),
    ('Swamp Thing', 'Alec Holland', 'Ageless', 'Male', 'Plant manipulation, elemental control, superhuman strength', 'Vulnerability to fire, limited mobility outside of plant life', 'Justice League Dark'),
    ('Raven', 'Raven Roth', 'Ageless', 'Female', 'Empathy, telekinesis, dark magic', 'Struggles with inner darkness, father\'s influence', 'Teen Titans'),
    ('Beast Boy', 'Garfield Logan', 20, 'Male', 'Shapeshifting into animals, enhanced agility', 'Struggles with identity, past traumas', 'Teen Titans'),
    ('Starfire', 'Koriand\'r', 'Ageless', 'Female', 'Flight, energy projection, superhuman strength', 'Struggles with cultural assimilation, past traumas', 'Teen Titans'),
    ('Cyborg', 'Victor Stone', 25, 'Male', 'Cybernetic enhancements, superhuman strength, technopathy', 'Struggles with humanity, cybernetic vulnerabilities', 'Teen Titans'),
    ('Nightwing', 'Dick Grayson', 30, 'Male', 'Acrobatics, martial arts mastery, detective skills', 'No superpowers, mortality', 'Teen Titans'),
    ('Red Hood', 'Jason Todd', 25, 'Male', 'Skilled marksman, hand-to-hand combatant, technology expertise', 'No superpowers, mortality, trauma', 'None'),
    ('Donna Troy', 'Donna Troy', 'Ageless', 'Female', 'Superhuman strength, flight, combat skills', 'Struggles with identity, past traumas', 'Teen Titans'),
    ('Aqualad', 'Kaldur\'ahm', 20, 'Male', 'Underwater adaptation, hydrokinetic powers', 'Struggles with loyalty, betrayal', 'Young Justice'),
    ('Artemis', 'Artemis Crock', 20, 'Female', 'Expert archer, combat skills', 'Struggles with trust, redemption', 'Young Justice'),
    ('Kid Flash', 'Wally West', 20, 'Male', 'Superhuman speed, agility', 'Impulsiveness, struggles with legacy', 'Young Justice'),
    ('Miss Martian', 'M\'gann M\'orzz', 20, 'Female', 'Telepathy, shape-shifting, flight', 'Struggles with identity, past traumas', 'Young Justice'),
    ('Superboy', 'Conner Kent', 20, 'Male', 'Superhuman strength, speed, durability', 'Struggles with identity, past traumas', 'Young Justice'),
    ('Blue Beetle', 'Jaime Reyes', 20, 'Male', 'Scarab-derived armor, flight, energy blasts', 'Struggles with controlling the scarab, vulnerability to mental influence', 'Young Justice'),
    ('Static', 'Virgil Hawkins', 18, 'Male', 'Electrokinesis, flight, electromagnetic manipulation', 'Struggles with responsibility, adolescence', 'Young Justice'),
    ('Robin', 'Tim Drake', 20, 'Male', 'Acrobatics, martial arts mastery, detective skills', 'No superpowers, mortality', 'Young Justice'),
    ]
    return heroes

def villains():
    villains = [
        ('Joker', 'Unknown', 'Male', 'Master of chaos, criminal genius', 'Psychopathy, obsession with Batman'),
        ('Lex Luthor', 'Unknown', 'Male', 'Genius-level intellect, business magnate', 'Obsession with defeating Superman, desire for power'),
        ('Harley Quinn', 'Harleen Quinzel', 'Female', 'Skilled gymnast, expert psychologist', 'Obsession with Joker, mental instability'),
        ('Darkseid', 'Uxas', 'Male', 'Superhuman strength, omega beams, immortality', 'Desire for universal domination, destruction'),
        ('Deathstroke', 'Slade Wilson', 'Male', 'Enhanced strength, agility, and reflexes, expert martial artist', 'Mercenary, tactical genius'),
        ('Catwoman', 'Selina Kyle', 'Female', 'Acrobatics, stealth, skilled hand-to-hand combatant', 'Cat burglar, complicated relationship with Batman'),
        ('Riddler', 'Edward Nygma', 'Male', 'Genius-level intellect, expert in puzzles and riddles', 'Obsession with riddles, compulsion to leave clues'),
        ('Two-Face', 'Harvey Dent', 'Male', 'Skilled strategist, dual personality', 'Driven by coin flips, obsession with duality'),
        ('Penguin', 'Oswald Cobblepot', 'Male', 'Criminal mastermind, skilled strategist', 'Obsession with birds, refined tastes'),
        ('Ra\'s al Ghul', 'Unknown', 'Male', 'Immortality, expert martial artist', 'Desire for global balance, eco-terrorism'),
        ('Black Adam', 'Teth-Adam', 'Male', 'Superhuman strength, speed, and stamina', 'Desire for power, vengeance against Shazam'),
        ('Sinestro', 'Thaal Sinestro', 'Male', 'Ability to generate and control yellow power ring constructs', 'Desire for control, manipulation'),
        ('Poison Ivy', 'Pamela Isley', 'Female', 'Control over plants, toxins, and pheromones', 'Environmental extremism, obsession with plants'),
        ('Scarecrow', 'Jonathan Crane', 'Male', 'Expert in fear toxins, skilled psychologist', 'Desire to spread fear, obsession with fear'),
        ('Bane', 'Unknown', 'Male', 'Genius-level intellect, peak physical condition', 'Venom dependency, obsession with Batman'),
        ('Mr. Freeze', 'Victor Fries', 'Male', 'Cryogenic technology, genius-level intellect', 'Desire to cure wife, obsession with ice'),
        ('Black Manta', 'David Hyde', 'Male', 'Enhanced strength, underwater survival, advanced technology', 'Obsession with Aquaman, desire for revenge'),
        ('Brainiac', 'Unknown', 'Male', 'Advanced intellect, vast knowledge, cybernetic enhancements', 'Desire for knowledge, collecting civilizations'),
        ('Mongul', 'Unknown', 'Male', 'Superhuman strength, invulnerability, energy projection', 'Desire for power, control over Warworld'),
        ('Cheetah', 'Barbara Ann Minerva', 'Female', 'Enhanced speed, strength, and agility', 'Obsession with power, jealousy towards Wonder Woman'),
        ('Gorilla Grodd', 'Unknown', 'Male', 'Superhuman strength, telepathy, genius-level intellect', 'Desire for power, world domination'),
        ('Man-Bat', 'Kirk Langstrom', 'Male', 'Human-bat hybrid, flight, echolocation', 'Obsession with power, loss of humanity'),
        ('Livewire', 'Leslie Willis', 'Female', 'Electrokinesis, electrical absorption, flight', 'Obsession with power, desire for revenge'),
        ('Vandal Savage', 'Unknown', 'Male', 'Immortality, enhanced strength, genius-level intellect', 'Desire for power, survival of the fittest'),
        ('Killer Croc', 'Waylon Jones', 'Male', 'Enhanced strength, reptilian physiology', 'Social rejection, identity issues'),
        ('Solomon Grundy', 'Cyrus Gold', 'Male', 'Superhuman strength, endurance, regeneration', 'Undead, lack of intelligence'),
        ('Atrocitus', 'Unknown', 'Male', 'Red power ring, blood magic', 'Desire for vengeance, rage against Guardians of the Universe'),
        ('Captain Cold', 'Leonard Snart', 'Male', 'Cryogenic weaponry, skilled tactician', 'Obsession with cold, desire for revenge on Flash'),
        ('Circe', 'Unknown', 'Female', 'Sorcery, immortality, shapeshifting', 'Obsession with power, hatred towards Wonder Woman'),
        ('Talia al Ghul', 'Unknown', 'Female', 'Master martial artist, expert strategist', 'Obsession with Batman, loyalty to Ra’s al Ghul'),
        ('Killer Frost', 'Caitlin Snow', 'Female', 'Cryokinesis, ice manipulation', 'Obsession with cold, desire for power'),
        ('Metallo', 'John Corben', 'Male', 'Cybernetic enhancements, Kryptonite power source', 'Obsession with Superman, desire for revenge'),
        ('Parasite', 'Unknown', 'Male', 'Energy absorption, superhuman strength', 'Obsession with power, desire to drain others'),
        ('Black Hand', 'William Hand', 'Male', 'Death energy manipulation, necromancy', 'Obsession with death, desire for destruction'),
        ('Giganta', 'Unknown', 'Female', 'Growth manipulation, superhuman strength', 'Desire for power, rivalry with Wonder Woman'),
        ('Eclipso', 'Bruce Gordon', 'Male', 'Possession, sorcery, manipulation', 'Obsession with power, desire for destruction'),
        ('Black Mask', 'Roman Sionis', 'Male', 'Criminal mastermind, skilled combatant', 'Obsession with masks, desire for control'),
        ('King Shark', 'Nanaue', 'Male', 'Superhuman strength, durability, enhanced senses', 'Cannibalistic tendencies, brute force'),
        ('Cheetah', 'Barbara Minerva', 'Female', 'Enhanced speed, strength, agility, and senses', 'Obsession with power, jealousy towards Wonder Woman'),
        ('Kite Man', 'Charles Brown', 'Male', 'Mastery of kites, skilled pilot', 'Low self-esteem, desire for recognition'),
        ('Mister Mxyzptlk', 'Unknown', 'Male', 'Reality manipulation, reality warping', 'Trickster nature, desire for amusement'),
        ('Harvey Two-Face', 'Harvey Dent', 'Male', 'Skilled strategist, dual personality', 'Driven by coin flips, obsession with duality'),
        ('Prometheus', 'Unknown', 'Male', 'Genius-level intellect, skilled martial artist', 'Obsession with vengeance, desire to destroy justice'),
        ('Toyman', 'Winslow Schott', 'Male', 'Mechanical expertise, toy-themed weapons', 'Obsession with toys, desire for chaos'),
    ]
    return villains
