def heroes():
    heroes = [
        ('Spider Man', 'Peter Parker', 18, 'Male', 'Wall-crawling, enhanced strength, spider-sense', 'Green Goblin, Venom, personal responsibility', 'Avengers'),
        ('Iron Man', 'Tony Stark', 35, 'Male', 'Genius-level intellect, powered armor suit', 'Alcoholism, arrogance, shrapnel near heart', 'Avengers'),
        ('Captain America', 'Steve Rogers', 100, 'Male', 'Peak human strength, master martial artist', 'Vulnerability to mental manipulation', 'Avengers'),
        ('Thor', 'Thor Odinson', 'Ageless', 'Male', 'Superhuman strength, lightning manipulation, Mjolnir', 'Arrogance, dependency on Mjolnir', 'Avengers'),
        ('Black Widow', 'Natasha Romanoff', 35, 'Female', 'Expert spy, martial artist, various weapons', 'Past traumas, guilt', 'Avengers'),
        ('Hulk', 'Bruce Banner', 40, 'Male', 'Superhuman strength, durability, gamma radiation', 'Rage, control issues', 'Avengers'),
        ('Wolverine', 'Logan', 'Ageless', 'Male', 'Regenerative healing factor, adamantium claws, enhanced senses', 'Memory loss, animalistic nature', 'X-Men'),
        ('Storm', 'Ororo Munroe', 35, 'Female', 'Weather manipulation, flight, leadership skills', 'Emotional instability, claustrophobia', 'X-Men'),
        ('Professor X', 'Charles Xavier', 65, 'Male', 'Telepathy, genius-level intellect, leadership skills', 'Paralysis, guilt over failures', 'X-Men'),
        ('Cyclops', 'Scott Summers', 35, 'Male', 'Optic blasts, tactical skills, leadership abilities', 'Struggles with leadership, emotional detachment', 'X-Men'),
        ('Jean Grey', 'Jean Grey', 35, 'Female', 'Telekinesis, telepathy, Phoenix Force', 'Struggles with dark side, loss of control', 'X-Men'),
        ('Beast', 'Hank McCoy', 40, 'Male', 'Superhuman strength, agility, genius intellect', 'Physical appearance, difficulty controlling transformations', 'X-Men'),
        ('Rogue', 'Anna Marie', 30, 'Female', 'Power absorption, flight, superhuman strength', 'Fear of hurting others, isolation', 'X-Men'),
        ('Gambit', 'Remy LeBeau', 35, 'Male', 'Kinetic energy manipulation, skilled thief, agility', 'Guilt over past actions, shady past', 'X-Men'),
        ('Nightcrawler', 'Kurt Wagner', 30, 'Male', 'Teleportation, agility, prehensile tail', 'Physical appearance, religious beliefs', 'X-Men'),
        ('Deadpool', 'Wade Wilson', 'Ageless', 'Male', 'Regenerative healing factor, expert marksman, fourth wall awareness', 'Mental instability, mercenary lifestyle', 'X-Force'),
        ('Black Panther', 'T\'Challa', 35, 'Male', 'Enhanced strength, agility, vibranium suit', 'Responsibility to Wakanda, struggles with tradition vs. progress', 'Avengers'),
        ('Doctor Strange', 'Stephen Strange', 45, 'Male', 'Mystic arts, time manipulation, astral projection', 'Arrogance, self-doubt, past mistakes', 'Avengers'),
        ('Ant Man', 'Scott Lang', 35, 'Male', 'Size manipulation, genius-level intellect, insect communication', 'Struggles with family responsibilities, past as a criminal', 'Avengers'),
        ('Wasp', 'Hope van Dyne', 30, 'Female', 'Size manipulation, wings, energy blasts', 'Guilt over past mistakes, family dynamics', 'Avengers'),
        ('Vision', 'Vision', 'Ageless', 'Male', 'Synthetic body, superhuman strength, density manipulation', 'Struggles with humanity, identity crisis', 'Avengers'),
        ('Daredevil', 'Matt Murdock', 35, 'Male', 'Enhanced senses, martial arts expertise, radar sense', 'Guilt over past failures, identity crisis', 'Defenders'),
        ('Luke Cage', 'Carl Lucas', 40, 'Male', 'Superhuman strength, invulnerability, unbreakable skin', 'Struggles with past, responsibility to community', 'Defenders'),
        ('Jessica Jones', 'Jessica Jones', 35, 'Female', 'Superhuman strength, flight, investigative skills', 'PTSD, struggles with past trauma', 'Defenders'),
        ('Iron Fist', 'Danny Rand', 35, 'Male', 'Martial arts mastery, chi manipulation, Iron Fist', 'Struggles with identity, duty as the Immortal Iron Fist', 'Defenders'),
        ('Punisher', 'Frank Castle', 40, 'Male', 'Expert marksman, hand-to-hand combatant, military training', 'Guilt over familys death, pursuit of justice through extreme methods', 'None'),
        ('Ghost Rider', 'Johnny Blaze', 'Ageless', 'Male', 'Flaming skull, superhuman strength, hellfire manipulation', 'Curse of the Ghost Rider, struggle with demonic side', 'Midnight Sons'),
        ('Silver Surfer', 'Norrin Radd', 'Ageless', 'Male', 'Cosmic power, superhuman strength, energy manipulation', 'Loss of humanity, servitude to Galactus', 'None'),
        ('Hawkeye', 'Clint Barton', 40, 'Male', 'Master archer, expert marksman, combat skills', 'Normal human vulnerabilities, struggles with past', 'Avengers'),
        ('Falcon', 'Sam Wilson', 40, 'Male', 'Flight, enhanced strength, expert hand-to-hand combatant', 'Struggles with past, responsibility to community', 'Avengers'),
        ('Scarlet Witch', 'Wanda Maximoff', 35, 'Female', 'Reality manipulation, chaos magic, telekinesis', 'Struggles with control, guilt over past actions', 'Avengers'),
        ('Quicksilver', 'Pietro Maximoff', 35, 'Male', 'Superhuman speed, agility, reflexes', 'Impulsiveness, rivalry with Magneto', 'Avengers'),
        ('Ms Marvel', 'Carol Danvers', 35, 'Female', 'Superhuman strength, flight, energy manipulation', 'Struggles with identity, past traumas', 'Avengers'),
        ('She Hulk', 'Jennifer Walters', 35, 'Female', 'Superhuman strength, durability, healing factor', 'Struggles with balancing life as lawyer and hero', 'Avengers'),
        ('Black Bolt', 'Blackagar Boltagon', 40, 'Male', 'Voice manipulation, superhuman strength, energy blasts', 'Responsibility to Attilan, speech limitations', 'Inhumans'),
        ('Medusa', 'Medusalith Amaquelin', 35, 'Female', 'Hair manipulation, superhuman strength, agility', 'Struggles with leadership, family dynamics', 'Inhumans'),
        ('Crystal', 'Crystalia Amaquelin', 30, 'Female', 'Elemental manipulation, flight, skilled combatant', 'Struggles with family dynamics, responsibilities', 'Inhumans'),
        ('Groot', 'Groot', 'Ageless', 'Male', 'Regeneration, superhuman strength, language limitations', 'Limited communication, sacrifices for friends', 'Guardians of the Galaxy'),
        ('Rocket Raccoon', 'Rocket Raccoon', 8, 'Male', 'Genius-level intellect, skilled marksman, cybernetic enhancements', 'Identity struggles, past trauma, size', 'Guardians of the Galaxy'),
        ('Star Lord', 'Peter Quill', 35, 'Male', 'Leadership skills, tactical expertise, advanced weaponry', 'Struggles with responsibility, relationships', 'Guardians of the Galaxy'),
        ('Gamora', 'Gamora', 35, 'Female', 'Master assassin, expert combatant, enhanced strength and agility', 'Struggles with past as Thanos\'s adopted daughter, redemption', 'Guardians of the Galaxy'),
        ('Drax the Destroyer', 'Drax', 'Ageless', 'Male', 'Superhuman strength, durability, expert combatant', 'Obsession with vengeance, literal thinking', 'Guardians of the Galaxy'),
        ('Mantis', 'Mantis', 35, 'Female', 'Empathy, skilled combatant, precognition', 'Struggles with social cues, past traumas', 'Guardians of the Galaxy'),
        ('Adam Warlock', 'Adam Warlock', 'Ageless', 'Male', 'Cosmic powers, energy manipulation, regeneration', 'Struggles with destiny, conflict with Magus', 'None'),
        ('Nova', 'Richard Rider', 25, 'Male', 'Energy manipulation, flight, enhanced strength', 'Struggles with responsibility, balancing life as hero and student', 'None'),
    ]
    return heroes

def villains():
    villains = [
        ('Green Goblin', 'Norman Osborn', 'Male', 'Superhuman strength, intelligence, glider', 'Hatred towards Spider-Man, insanity'),
        ('Venom', 'Eddie Brock', 'Male', 'Symbiote suit grants superhuman strength, agility, and durability', 'Hatred towards Spider-Man, symbiote weaknesses'),
        ('Loki', 'Loki Laufeyson', 'Male', 'Illusions, sorcery, shapeshifting, superhuman abilities', 'Desire for power, jealousy towards Thor'),
        ('Thanos', 'Thanos', 'Male', 'Superhuman strength, durability, energy manipulation', 'Obsession with Death, quest for the Infinity Stones'),
        ('Magneto', 'Erik Lehnsherr', 'Male', 'Magnetism manipulation, control over metal objects', 'Hatred towards humans, desire for mutant supremacy'),
        ('Doctor Octopus', 'Otto Octavius', 'Male', 'Mechanical tentacles, genius-level intellect', 'Obsession with proving superiority, criminal ambition'),
        ('Red Skull', 'Johann Schmidt', 'Male', 'Peak human strength, strategic genius, skilled combatant', 'Nazi ideology, obsession with power, hatred towards Captain America'),
        ('Ultron', 'Ultron', 'N/A', 'Artificial intelligence, superhuman strength, energy manipulation', 'Desire to exterminate humanity, superiority complex'),
        ('Kingpin', 'Wilson Fisk', 'Male', 'Master strategist, peak human strength, extensive criminal empire', 'Control freak, desire for power and control'),
        ('Apocalypse', 'En Sabah Nur', 'Male', 'Superhuman strength, invulnerability, molecular manipulation', 'Desire for survival of the fittest, destruction, evolution'),
        ('Mystique', 'Raven Darkholme', 'Female', 'Shapeshifting, martial arts, deception', 'Lack of moral compass, loyalty to Magneto'),
        ('Juggernaut', 'Cain Marko', 'Male', 'Unstoppable momentum, superhuman strength, invulnerability', 'Obsession with destruction, hatred towards Xavier and the X-Men'),
        ('Galactus', 'Galactus', 'Male', 'Cosmic entity, immense cosmic power, energy manipulation', 'Consumes planets for sustenance, indifferent to life'),
        ('Venom (Symbiote)', 'Symbiote', 'N/A', 'Symbiote suit grants superhuman strength, agility, and durability', 'Desire for a host, aggressive tendencies'),
        ('Carnage', 'Cletus Kasady', 'Male', 'Symbiote suit grants superhuman strength, agility, and durability', 'Psychopathic tendencies, desire for chaos and destruction'),
        ('Mephisto', 'Mephistopheles', 'Male', 'Demon, reality manipulation, manipulation of souls', 'Desire for corrupting souls, gaining power'),
        ('Doctor Doom', 'Victor von Doom', 'Male', 'Genius-level intellect, mastery of sorcery and science, armored suit', 'Desire for world domination, rivalry with Reed Richards'),
        ('Taskmaster', 'Tony Masters', 'Male', 'Photographic reflexes, master martial artist, skilled marksman', 'Mercenary, lack of empathy, amoral'),
        ('Sabretooth', 'Victor Creed', 'Male', 'Superhuman senses, strength, agility, healing factor', 'Bloodlust, sadistic tendencies, rivalry with Wolverine'),
        ('The Vulture', 'Adrian Toomes', 'Male', 'Powered flight, enhanced strength, aging reversal technology', 'Obsession with youth, revenge, hatred towards Spider-Man'),
        ('Bullseye', 'Lester Poindexter', 'Male', 'Expert marksman, perfect aim, skilled combatant', 'Psychopathic tendencies, obsession with perfection, hired killer'),
        ('The Mandarin', 'Unknown', 'Male', 'Mastery of martial arts, ten power rings', 'Desire for power, world domination, revenge against Iron Man'),
        ('Hela', 'Hela', 'Female', 'Superhuman strength, control over death, sorcery', 'Desire for power, control over Hel, revenge against Thor'),
        ('Baron Zemo', 'Helmut Zemo', 'Male', 'Master strategist, skilled combatant, leadership abilities', 'Hatred towards Captain America, desire for revenge and power'),
        ('Abomination', 'Emil Blonsky', 'Male', 'Superhuman strength, durability, regeneration', 'Rage, loss of humanity, rivalry with Hulk'),
        ('Mr Sinister', 'Nathaniel Essex', 'Male', 'Genius-level intellect, genetic manipulation, immortality', 'Obsession with evolution, manipulation, desire for power'),
        ('Hobgoblin', 'Various', 'Male', 'Superhuman strength, intelligence, glider, pumpkin bombs', 'Hatred towards Spider-Man, insanity, rivalry with Green Goblin'),
        ('The Leader', 'Samuel Sterns', 'Male', 'Genius-level intellect, superhuman intelligence, psionic powers', 'Desire for power, control, rivalry with Hulk'),
        ('Enchantress', 'Amora', 'Female', 'Sorcery, manipulation, seduction', 'Desire for power, control over men, rivalry with Thor'),
        ('Annihilus', 'Annihilus', 'Male', 'Superhuman strength, energy blasts, control over Negative Zone', 'Desire for conquest, destruction, control over Annihilation Wave'),
        ('Kraven the Hunter', 'Sergei Kravinoff', 'Male', 'Peak human strength, expert hunter, skilled combatant', 'Obsession with hunting, defeating Spider-Man, proving superiority'),
        # Add more villains here...
    ]
    return villains
